version: '3.1'
services:
  postgres:
    image: postgres:10.1
    hostname: "postgres"
    labels:
      name: "postgres"
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
