version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    restart: always
    ports:
      - "15673:15672"
      - "5673:5672"
    labels:
      name: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
